### ISSUE TITLE
Bug no Encaminhamento de Mensagens

### ISSUE THREAD

**Issue by uira** [R4dar/radar-web#10]
#BUG #Critico

![captura de tela 2018-04-19 as 13 39 56](https://user-images.githubusercontent.com/89998/39005671-3021e8c0-43d7-11e8-97c6-adc7b45eda28.png)

no modal de encaminhamento de mensagem, não aparece a lista de destinatários.

**Comment by albertosouza** [comment]
Bug corrigido na versão 1.0.7
